services:
  - type: web
    name: ecommerce-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: ecommerce
